apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: overmind-api
  labels:
    app: overmind
    component: api
spec:
  http:
  - name: primary
    route:
    - destination:
        host: overmind-api-stable
      weight: 100
    - destination:
        host: overmind-api-canary
      weight: 0
  gateways:
  - istio-system/istio-gateway
  hosts:
  - api.overmind.dev
